import defaultTheme from 'tailwindcss/defaultTheme';
import forms from '@tailwindcss/forms';

/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],

    theme: {
        extend: {
            colors: {
                "on-tertiary": "#ffffff",
                "inverse-on-surface": "#f0f1f1",
                "on-error": "#ffffff",
                "error": "#ba1a1a",
                "on-background": "#1a1c1c",
                "slate-300": "#9499a3",
                "slate-200": "#aeb2ba",
                "on-tertiary-fixed-variant": "#444749",
                "error-container": "#ffdad6",
                "on-secondary": "#ffffff",
                "slate-600": "#4d5464",
                "slate-100": "#c8cbd0",
                "inverse-surface": "#2f3131",
                "on-primary-fixed": "#131b2e",
                "on-secondary-fixed-variant": "#414755",
                "primary-fixed": "#dae2fd",
                "slate-400": "#7c818e",
                "primary-container": "#131b2e",
                "inverse-primary": "#bec6e0",
                "on-surface-variant": "#45464d",
                "slate-500": "#646a79",
                "slate-50": "#e3e5e7",
                "surface-container-low": "#f3f3f4",
                "tertiary-container": "#191c1e",
                "surface-container-high": "#e8e8e8",
                "on-error-container": "#93000a",
                "surface-container": "#eeeeee",
                "on-tertiary-container": "#818486",
                "on-surface": "#1a1c1c",
                "slate-700": "#373f50",
                "surface-tint": "#565e74",
                "slate-800": "#222a3d",
                "primary": "#000000",
                "surface-container-highest": "#e2e2e2",
                "tertiary-fixed": "#e0e3e5",
                "outline": "#76777d",
                "surface-dim": "#dadada",
                "surface-bright": "#f9f9f9",
                "secondary-fixed": "#dde2f4",
                "background": "#f9f9f9",
                "on-primary": "#ffffff",
                "outline-variant": "#c6c6cd",
                "tertiary": "#000000",
                "on-primary-container": "#7c839b",
                "surface-container-lowest": "#ffffff",
                "on-primary-fixed-variant": "#3f465c",
                "secondary-fixed-dim": "#c1c6d7",
                "surface": "#f9f9f9",
                "on-secondary-container": "#5e6473",
                "on-secondary-fixed": "#151c28",
                "slate-900": "#0f172a",
                "primary-fixed-dim": "#bec6e0",
                "secondary-container": "#dde2f4",
                "secondary": "#585e6d",
                "surface-variant": "#e2e2e2",
                "tertiary-fixed-dim": "#c4c7c9",
                "on-tertiary-fixed": "#191c1e"
            },
            borderRadius: {
                "DEFAULT": "0.25rem",
                "lg": "0.5rem",
                "xl": "0.75rem",
                "full": "9999px"
            },
            spacing: {
                "sm": "8px",
                "margin-desktop": "64px",
                "xxl": "48px",
                "xs": "4px",
                "margin-mobile": "16px",
                "xl": "32px",
                "base": "8px",
                "lg": "24px",
                "gutter": "24px",
                "md": "16px"
            },
            fontFamily: {
                sans: ['Plus Jakarta Sans', ...defaultTheme.fontFamily.sans],
                "headline-xxl-mobile": ["Plus Jakarta Sans"],
                "headline-xxl": ["Plus Jakarta Sans"],
                "headline-sm": ["Plus Jakarta Sans"],
                "body-md": ["Plus Jakarta Sans"],
                "body-sm": ["Plus Jakarta Sans"],
                "body-lg": ["Plus Jakarta Sans"],
                "code": ["ui-monospace"],
                "headline-xl-mobile": ["Plus Jakarta Sans"],
                "headline-md": ["Plus Jakarta Sans"],
                "headline-lg": ["Plus Jakarta Sans"],
                "headline-xl": ["Plus Jakarta Sans"]
            },
            fontSize: {
                "headline-xxl-mobile": ["36px", { "lineHeight": "44px", "letterSpacing": "-0.75px", "fontWeight": "700" }],
                "headline-xxl": ["60px", { "lineHeight": "75px", "letterSpacing": "-1.5px", "fontWeight": "700" }],
                "headline-sm": ["16px", { "lineHeight": "22.5px", "letterSpacing": "-0.45px", "fontWeight": "700" }],
                "body-md": ["14px", { "lineHeight": "20px", "letterSpacing": "0.3px", "fontWeight": "500" }],
                "body-sm": ["11px", { "lineHeight": "13.75px", "letterSpacing": "2.75px", "fontWeight": "500" }],
                "body-lg": ["16px", { "lineHeight": "24px", "letterSpacing": "normal", "fontWeight": "500" }],
                "code": ["12px", { "lineHeight": "16px", "letterSpacing": "1.2px", "fontWeight": "400" }],
                "headline-xl-mobile": ["28px", { "lineHeight": "36px", "letterSpacing": "normal", "fontWeight": "700" }],
                "headline-md": ["18px", { "lineHeight": "24.75px", "letterSpacing": "normal", "fontWeight": "700" }],
                "headline-lg": ["32px", { "lineHeight": "40px", "letterSpacing": "-0.45px", "fontWeight": "700" }],
                "headline-xl": ["48px", { "lineHeight": "60px", "letterSpacing": "normal", "fontWeight": "700" }]
            }
        },
    },

    plugins: [forms],
};
